#!/usr/bin/env php
<?php
set_time_limit(0);

require __DIR__ . '/../src/bootstrap.php';

//use Symfony\Component\Console\Application;
use Abbiya\Watcher\Tool\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

$container = new ContainerBuilder();
$loader = new YamlFileLoader($container, new FileLocator(__DIR__ . '/conf'));
$loader->load('services.yml');

$container->setParameter('base.path', __DIR__);

$application = new Application();

$application->add($container->get('watch.command'));

$application->run();
